/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.indexes


import com.backend.jooq.tables.Audits
import com.backend.jooq.tables.Users

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_AUDITS_TIMESTAMP: Index = Internal.createIndex(DSL.name("idx_audits_timestamp"), Audits.AUDITS, arrayOf(Audits.AUDITS.timestamp.desc()), false)
val IDX_USERS_UNIQUE_EMAIL: Index = Internal.createIndex(DSL.name("idx_users_unique_email"), Users.USERS, arrayOf(Users.USERS.email), true)
