/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.tables


import com.backend.jooq.Public
import com.backend.jooq.indexes.IDX_AUDITS_TIMESTAMP
import com.backend.jooq.keys.AUDITS_PKEY
import com.backend.jooq.keys.AUDITS__AUDITS_USERID_FKEY
import com.backend.jooq.tables.Users.UsersPath
import com.backend.jooq.tables.records.AuditsRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Audits(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AuditsRecord>?,
    parentPath: InverseForeignKey<out Record, AuditsRecord>?,
    aliased: Table<AuditsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AuditsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.audits</code>
         */
        val AUDITS: Audits = Audits()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AuditsRecord> = AuditsRecord::class.java

    /**
     * The column <code>public.audits.id</code>.
     */
    val id: TableField<AuditsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.audits.message</code>.
     */
    val message: TableField<AuditsRecord, String?> = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.audits.payload</code>.
     */
    val payload: TableField<AuditsRecord, JSONB?> = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "")

    /**
     * The column <code>public.audits.result</code>.
     */
    val result: TableField<AuditsRecord, JSONB?> = createField(DSL.name("result"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.audits.userId</code>.
     */
    val userId: TableField<AuditsRecord, UUID?> = createField(DSL.name("userId"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.audits.timestamp</code>.
     */
    val timestamp: TableField<AuditsRecord, LocalDateTime?> = createField(DSL.name("timestamp"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<AuditsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AuditsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AuditsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.audits</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.audits</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.audits</code> table reference
     */
    constructor(): this(DSL.name("audits"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AuditsRecord>?, parentPath: InverseForeignKey<out Record, AuditsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, AUDITS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AuditsPath : Audits, Path<AuditsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AuditsRecord>?, parentPath: InverseForeignKey<out Record, AuditsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AuditsRecord>): super(alias, aliased)
        override fun `as`(alias: String): AuditsPath = AuditsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AuditsPath = AuditsPath(alias, this)
        override fun `as`(alias: Table<*>): AuditsPath = AuditsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_AUDITS_TIMESTAMP)
    override fun getPrimaryKey(): UniqueKey<AuditsRecord> = AUDITS_PKEY
    override fun getReferences(): List<ForeignKey<AuditsRecord, *>> = listOf(AUDITS__AUDITS_USERID_FKEY)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, AUDITS__AUDITS_USERID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): Audits = Audits(DSL.name(alias), this)
    override fun `as`(alias: Name): Audits = Audits(alias, this)
    override fun `as`(alias: Table<*>): Audits = Audits(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Audits = Audits(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Audits = Audits(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Audits = Audits(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Audits = Audits(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Audits = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Audits = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Audits = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Audits = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Audits = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Audits = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Audits = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Audits = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Audits = where(DSL.notExists(select))
}
