/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.tables


import com.backend.jooq.Public
import com.backend.jooq.enums.TasksPriorityEnum
import com.backend.jooq.enums.TasksStatusEnum
import com.backend.jooq.indexes.IDX_TASKS_ASSIGNEE
import com.backend.jooq.indexes.IDX_TASKS_PRIORITY
import com.backend.jooq.indexes.IDX_TASKS_STATUS
import com.backend.jooq.keys.TASKS_PKEY
import com.backend.jooq.keys.TASKS__TASKS_ASSIGNEEID_FKEY
import com.backend.jooq.tables.Users.UsersPath
import com.backend.jooq.tables.records.TasksRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Tasks(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TasksRecord>?,
    parentPath: InverseForeignKey<out Record, TasksRecord>?,
    aliased: Table<TasksRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TasksRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.tasks</code>
         */
        val TASKS: Tasks = Tasks()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TasksRecord> = TasksRecord::class.java

    /**
     * The column <code>public.tasks.id</code>.
     */
    val id: TableField<TasksRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.tasks.title</code>.
     */
    val title: TableField<TasksRecord, String?> = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.tasks.description</code>.
     */
    val description: TableField<TasksRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.tasks.status</code>.
     */
    val status: TableField<TasksRecord, TasksStatusEnum?> = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'TODO'::tasks_status_enum"), SQLDataType.VARCHAR)).asEnumDataType(TasksStatusEnum::class.java), this, "")

    /**
     * The column <code>public.tasks.priority</code>.
     */
    val priority: TableField<TasksRecord, TasksPriorityEnum?> = createField(DSL.name("priority"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'MEDIUM'::tasks_priority_enum"), SQLDataType.VARCHAR)).asEnumDataType(TasksPriorityEnum::class.java), this, "")

    /**
     * The column <code>public.tasks.assigneeId</code>.
     */
    val assigneeId: TableField<TasksRecord, UUID?> = createField(DSL.name("assigneeId"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.tasks.deleted</code>.
     */
    val deleted: TableField<TasksRecord, Boolean?> = createField(DSL.name("deleted"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.tasks.createdAt</code>.
     */
    val createdAt: TableField<TasksRecord, LocalDateTime?> = createField(DSL.name("createdAt"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.tasks.modifiedAt</code>.
     */
    val modifiedAt: TableField<TasksRecord, LocalDateTime?> = createField(DSL.name("modifiedAt"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<TasksRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TasksRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TasksRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.tasks</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.tasks</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.tasks</code> table reference
     */
    constructor(): this(DSL.name("tasks"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TasksRecord>?, parentPath: InverseForeignKey<out Record, TasksRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TASKS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TasksPath : Tasks, Path<TasksRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TasksRecord>?, parentPath: InverseForeignKey<out Record, TasksRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TasksRecord>): super(alias, aliased)
        override fun `as`(alias: String): TasksPath = TasksPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TasksPath = TasksPath(alias, this)
        override fun `as`(alias: Table<*>): TasksPath = TasksPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_TASKS_ASSIGNEE, IDX_TASKS_PRIORITY, IDX_TASKS_STATUS)
    override fun getPrimaryKey(): UniqueKey<TasksRecord> = TASKS_PKEY
    override fun getReferences(): List<ForeignKey<TasksRecord, *>> = listOf(TASKS__TASKS_ASSIGNEEID_FKEY)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, TASKS__TASKS_ASSIGNEEID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): Tasks = Tasks(DSL.name(alias), this)
    override fun `as`(alias: Name): Tasks = Tasks(alias, this)
    override fun `as`(alias: Table<*>): Tasks = Tasks(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Tasks = Tasks(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Tasks = Tasks(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Tasks = Tasks(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Tasks = Tasks(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Tasks = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Tasks = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Tasks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Tasks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Tasks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Tasks = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Tasks = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Tasks = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Tasks = where(DSL.notExists(select))
}
