/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq


import com.backend.jooq.tables.Audits
import com.backend.jooq.tables.Tasks
import com.backend.jooq.tables.Users

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.audits</code>.
     */
    val AUDITS: Audits get() = Audits.AUDITS

    /**
     * The table <code>public.tasks</code>.
     */
    val TASKS: Tasks get() = Tasks.TASKS

    /**
     * The table <code>public.users</code>.
     */
    val USERS: Users get() = Users.USERS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Audits.AUDITS,
        Tasks.TASKS,
        Users.USERS
    )
}
