/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.keys


import com.backend.jooq.tables.Audits
import com.backend.jooq.tables.Users
import com.backend.jooq.tables.records.AuditsRecord
import com.backend.jooq.tables.records.UsersRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val AUDITS_PKEY: UniqueKey<AuditsRecord> = Internal.createUniqueKey(Audits.AUDITS, DSL.name("audits_pkey"), arrayOf(Audits.AUDITS.id), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), arrayOf(Users.USERS.id), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val AUDITS__AUDITS_USERID_FKEY: ForeignKey<AuditsRecord, UsersRecord> = Internal.createForeignKey(Audits.AUDITS, DSL.name("audits_userId_fkey"), arrayOf(Audits.AUDITS.userId), com.backend.jooq.keys.USERS_PKEY, arrayOf(Users.USERS.id), true)
