/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.tables.records


import com.backend.jooq.tables.Audits

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuditsRecord private constructor() : UpdatableRecordImpl<AuditsRecord>(Audits.AUDITS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var message: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var payload: JSONB?
        set(value): Unit = set(2, value)
        get(): JSONB? = get(2) as JSONB?

    open var result: JSONB?
        set(value): Unit = set(3, value)
        get(): JSONB? = get(3) as JSONB?

    open var userId: UUID?
        set(value): Unit = set(4, value)
        get(): UUID? = get(4) as UUID?

    open var timestamp: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised AuditsRecord
     */
    constructor(id: UUID? = null, message: String, payload: JSONB? = null, result: JSONB? = null, userId: UUID? = null, timestamp: LocalDateTime? = null): this() {
        this.id = id
        this.message = message
        this.payload = payload
        this.result = result
        this.userId = userId
        this.timestamp = timestamp
        resetChangedOnNotNull()
    }
}
