/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.tables.records


import com.backend.jooq.enums.TasksPriorityEnum
import com.backend.jooq.enums.TasksStatusEnum
import com.backend.jooq.tables.Tasks

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TasksRecord private constructor() : UpdatableRecordImpl<TasksRecord>(Tasks.TASKS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var title: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var status: TasksStatusEnum?
        set(value): Unit = set(3, value)
        get(): TasksStatusEnum? = get(3) as TasksStatusEnum?

    open var priority: TasksPriorityEnum?
        set(value): Unit = set(4, value)
        get(): TasksPriorityEnum? = get(4) as TasksPriorityEnum?

    open var assigneeId: UUID?
        set(value): Unit = set(5, value)
        get(): UUID? = get(5) as UUID?

    open var deleted: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    open var modifiedAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised TasksRecord
     */
    constructor(id: UUID? = null, title: String, description: String? = null, status: TasksStatusEnum? = null, priority: TasksPriorityEnum? = null, assigneeId: UUID? = null, deleted: Boolean? = null, createdAt: LocalDateTime? = null, modifiedAt: LocalDateTime? = null): this() {
        this.id = id
        this.title = title
        this.description = description
        this.status = status
        this.priority = priority
        this.assigneeId = assigneeId
        this.deleted = deleted
        this.createdAt = createdAt
        this.modifiedAt = modifiedAt
        resetChangedOnNotNull()
    }
}
