/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.tables.records


import com.backend.jooq.enums.UsersRoleEnum
import com.backend.jooq.tables.Users

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersRecord private constructor() : UpdatableRecordImpl<UsersRecord>(Users.USERS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var email: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var password: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var role: UsersRoleEnum?
        set(value): Unit = set(3, value)
        get(): UsersRoleEnum? = get(3) as UsersRoleEnum?

    open var deleted: Boolean?
        set(value): Unit = set(4, value)
        get(): Boolean? = get(4) as Boolean?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var modifiedAt: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: UUID? = null, email: String, password: String, role: UsersRoleEnum? = null, deleted: Boolean? = null, createdAt: LocalDateTime? = null, modifiedAt: LocalDateTime? = null): this() {
        this.id = id
        this.email = email
        this.password = password
        this.role = role
        this.deleted = deleted
        this.createdAt = createdAt
        this.modifiedAt = modifiedAt
        resetChangedOnNotNull()
    }
}
