/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.enums


import com.backend.jooq.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class TasksPriorityEnum(@get:JvmName("literal") public val literal: String) : EnumType {
    LOW("LOW"),
    MEDIUM("MEDIUM"),
    HIGH("HIGH");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "tasks_priority_enum"
    override fun getLiteral(): String = literal
}
