/*
 * This file is generated by jOOQ.
 */
package com.backend.jooq.enums


import com.backend.jooq.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class UsersRoleEnum(@get:JvmName("literal") public val literal: String) : EnumType {
    USER("USER"),
    ADMIN("ADMIN");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "users_role_enum"
    override fun getLiteral(): String = literal
}
