/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'

const homeRouteRoute = homeRouteRouteImport.update({
            id: '/(home)',getParentRoute: () => rootRouteImport
          }as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
            id: '/auth/',path: '/auth/',getParentRoute: () => rootRouteImport
          }as any)
const homeIndexRoute = homeIndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => homeRouteRoute
          }as any)

export interface FileRoutesByFullPath {
'/': typeof homeIndexRoute,'/auth': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
'/': typeof homeIndexRoute,'/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
'__root__': typeof rootRouteImport,
'/(home)': typeof homeRouteRouteWithChildren,'/(home)/': typeof homeIndexRoute,'/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
fileRoutesByFullPath: FileRoutesByFullPath
fullPaths: '/'|'/auth'
fileRoutesByTo: FileRoutesByTo
to: '/'|'/auth'
id: '__root__'|'/(home)'|'/(home)/'|'/auth/'
fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
homeRouteRoute: typeof homeRouteRouteWithChildren,AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
          id: '/(home)'
          path: ''
          fullPath: ''
          preLoaderRoute: typeof homeRouteRouteImport
          parentRoute: typeof rootRouteImport
        }
'/auth/': {
          id: '/auth/'
          path: '/auth'
          fullPath: '/auth'
          preLoaderRoute: typeof AuthIndexRouteImport
          parentRoute: typeof rootRouteImport
        }
'/(home)/': {
          id: '/(home)/'
          path: '/'
          fullPath: '/'
          preLoaderRoute: typeof homeIndexRouteImport
          parentRoute: typeof homeRouteRoute
        }
  }
}



interface homeRouteRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeIndexRoute: homeIndexRoute
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(homeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  homeRouteRoute: homeRouteRouteWithChildren,AuthIndexRoute: AuthIndexRoute
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()