/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeRouteRouteImport } from './routes/(home)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as homeUsersIndexRouteImport } from './routes/(home)/users/index'
import { Route as homeRealtimeIndexRouteImport } from './routes/(home)/realtime/index'
import { Route as homeProfileIndexRouteImport } from './routes/(home)/profile/index'
import { Route as homeGraphIndexRouteImport } from './routes/(home)/graph/index'
import { Route as homeAuditIndexRouteImport } from './routes/(home)/audit/index'

const homeRouteRoute = homeRouteRouteImport.update({
            id: '/(home)',getParentRoute: () => rootRouteImport
          }as any)
const IndexRoute = IndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => rootRouteImport
          }as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
            id: '/auth/',path: '/auth/',getParentRoute: () => rootRouteImport
          }as any)
const homeUsersIndexRoute = homeUsersIndexRouteImport.update({
            id: '/users/',path: '/users/',getParentRoute: () => homeRouteRoute
          }as any)
const homeRealtimeIndexRoute = homeRealtimeIndexRouteImport.update({
            id: '/realtime/',path: '/realtime/',getParentRoute: () => homeRouteRoute
          }as any)
const homeProfileIndexRoute = homeProfileIndexRouteImport.update({
            id: '/profile/',path: '/profile/',getParentRoute: () => homeRouteRoute
          }as any)
const homeGraphIndexRoute = homeGraphIndexRouteImport.update({
            id: '/graph/',path: '/graph/',getParentRoute: () => homeRouteRoute
          }as any)
const homeAuditIndexRoute = homeAuditIndexRouteImport.update({
            id: '/audit/',path: '/audit/',getParentRoute: () => homeRouteRoute
          }as any)

export interface FileRoutesByFullPath {
'/': typeof IndexRoute,'/auth': typeof AuthIndexRoute,'/audit': typeof homeAuditIndexRoute,'/graph': typeof homeGraphIndexRoute,'/profile': typeof homeProfileIndexRoute,'/realtime': typeof homeRealtimeIndexRoute,'/users': typeof homeUsersIndexRoute
}
export interface FileRoutesByTo {
'/': typeof IndexRoute,'/auth': typeof AuthIndexRoute,'/audit': typeof homeAuditIndexRoute,'/graph': typeof homeGraphIndexRoute,'/profile': typeof homeProfileIndexRoute,'/realtime': typeof homeRealtimeIndexRoute,'/users': typeof homeUsersIndexRoute
}
export interface FileRoutesById {
'__root__': typeof rootRouteImport,
'/': typeof IndexRoute,'/(home)': typeof homeRouteRouteWithChildren,'/auth/': typeof AuthIndexRoute,'/(home)/audit/': typeof homeAuditIndexRoute,'/(home)/graph/': typeof homeGraphIndexRoute,'/(home)/profile/': typeof homeProfileIndexRoute,'/(home)/realtime/': typeof homeRealtimeIndexRoute,'/(home)/users/': typeof homeUsersIndexRoute
}
export interface FileRouteTypes {
fileRoutesByFullPath: FileRoutesByFullPath
fullPaths: '/'|'/auth'|'/audit'|'/graph'|'/profile'|'/realtime'|'/users'
fileRoutesByTo: FileRoutesByTo
to: '/'|'/auth'|'/audit'|'/graph'|'/profile'|'/realtime'|'/users'
id: '__root__'|'/'|'/(home)'|'/auth/'|'/(home)/audit/'|'/(home)/graph/'|'/(home)/profile/'|'/(home)/realtime/'|'/(home)/users/'
fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
IndexRoute: typeof IndexRoute,homeRouteRoute: typeof homeRouteRouteWithChildren,AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)': {
          id: '/(home)'
          path: ''
          fullPath: ''
          preLoaderRoute: typeof homeRouteRouteImport
          parentRoute: typeof rootRouteImport
        }
'/': {
          id: '/'
          path: '/'
          fullPath: '/'
          preLoaderRoute: typeof IndexRouteImport
          parentRoute: typeof rootRouteImport
        }
'/auth/': {
          id: '/auth/'
          path: '/auth'
          fullPath: '/auth'
          preLoaderRoute: typeof AuthIndexRouteImport
          parentRoute: typeof rootRouteImport
        }
'/(home)/users/': {
          id: '/(home)/users/'
          path: '/users'
          fullPath: '/users'
          preLoaderRoute: typeof homeUsersIndexRouteImport
          parentRoute: typeof homeRouteRoute
        }
'/(home)/realtime/': {
          id: '/(home)/realtime/'
          path: '/realtime'
          fullPath: '/realtime'
          preLoaderRoute: typeof homeRealtimeIndexRouteImport
          parentRoute: typeof homeRouteRoute
        }
'/(home)/profile/': {
          id: '/(home)/profile/'
          path: '/profile'
          fullPath: '/profile'
          preLoaderRoute: typeof homeProfileIndexRouteImport
          parentRoute: typeof homeRouteRoute
        }
'/(home)/graph/': {
          id: '/(home)/graph/'
          path: '/graph'
          fullPath: '/graph'
          preLoaderRoute: typeof homeGraphIndexRouteImport
          parentRoute: typeof homeRouteRoute
        }
'/(home)/audit/': {
          id: '/(home)/audit/'
          path: '/audit'
          fullPath: '/audit'
          preLoaderRoute: typeof homeAuditIndexRouteImport
          parentRoute: typeof homeRouteRoute
        }
  }
}



interface homeRouteRouteChildren {
  homeAuditIndexRoute: typeof homeAuditIndexRoute,homeGraphIndexRoute: typeof homeGraphIndexRoute,homeProfileIndexRoute: typeof homeProfileIndexRoute,homeRealtimeIndexRoute: typeof homeRealtimeIndexRoute,homeUsersIndexRoute: typeof homeUsersIndexRoute
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeAuditIndexRoute: homeAuditIndexRoute,homeGraphIndexRoute: homeGraphIndexRoute,homeProfileIndexRoute: homeProfileIndexRoute,homeRealtimeIndexRoute: homeRealtimeIndexRoute,homeUsersIndexRoute: homeUsersIndexRoute
}

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(homeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,homeRouteRoute: homeRouteRouteWithChildren,AuthIndexRoute: AuthIndexRoute
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()